/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedItRouteImport } from './routes/_authenticated/it'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated/facilities'
import { Route as AuthenticatedCfoRouteImport } from './routes/_authenticated/cfo'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItRoute = AuthenticatedItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCfoRoute = AuthenticatedCfoRouteImport.update({
  id: '/cfo',
  path: '/cfo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/cfo': typeof AuthenticatedCfoRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/it': typeof AuthenticatedItRoute
  '/operations': typeof AuthenticatedOperationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/cfo': typeof AuthenticatedCfoRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/it': typeof AuthenticatedItRoute
  '/operations': typeof AuthenticatedOperationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRoute
  '/_authenticated/cfo': typeof AuthenticatedCfoRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/it': typeof AuthenticatedItRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ceo'
    | '/cfo'
    | '/facilities'
    | '/finance'
    | '/it'
    | '/operations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ceo'
    | '/cfo'
    | '/facilities'
    | '/finance'
    | '/it'
    | '/operations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ceo'
    | '/_authenticated/cfo'
    | '/_authenticated/facilities'
    | '/_authenticated/finance'
    | '/_authenticated/it'
    | '/_authenticated/operations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/it': {
      id: '/_authenticated/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof AuthenticatedItRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cfo': {
      id: '/_authenticated/cfo'
      path: '/cfo'
      fullPath: '/cfo'
      preLoaderRoute: typeof AuthenticatedCfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRoute
  AuthenticatedCfoRoute: typeof AuthenticatedCfoRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedItRoute: typeof AuthenticatedItRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCeoRoute: AuthenticatedCeoRoute,
  AuthenticatedCfoRoute: AuthenticatedCfoRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedItRoute: AuthenticatedItRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
