/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedItRouteImport } from './routes/_authenticated/it'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated/facilities'
import { Route as AuthenticatedCfoRouteImport } from './routes/_authenticated/cfo'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations.index'
import { Route as AuthenticatedItIndexRouteImport } from './routes/_authenticated/it.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedFacilitiesIndexRouteImport } from './routes/_authenticated/facilities.index'
import { Route as AuthenticatedCfoIndexRouteImport } from './routes/_authenticated/cfo.index'
import { Route as AuthenticatedCeoIndexRouteImport } from './routes/_authenticated/ceo.index'
import { Route as AuthenticatedFinanceValidationRouteImport } from './routes/_authenticated/finance.validation'
import { Route as AuthenticatedFinanceReconciliationRouteImport } from './routes/_authenticated/finance.reconciliation'
import { Route as AuthenticatedFinanceMastersRouteImport } from './routes/_authenticated/finance.masters'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated/finance.invoices'
import { Route as AuthenticatedCfoPnlRouteImport } from './routes/_authenticated/cfo.pnl'
import { Route as AuthenticatedCfoInvoicesRouteImport } from './routes/_authenticated/cfo.invoices'
import { Route as AuthenticatedCfoAuditRouteImport } from './routes/_authenticated/cfo.audit'
import { Route as AuthenticatedCfoApprovalsRouteImport } from './routes/_authenticated/cfo.approvals'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItRoute = AuthenticatedItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCfoRoute = AuthenticatedCfoRouteImport.update({
  id: '/cfo',
  path: '/cfo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperationsRoute,
  } as any)
const AuthenticatedItIndexRoute = AuthenticatedItIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedItRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFacilitiesIndexRoute =
  AuthenticatedFacilitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFacilitiesRoute,
  } as any)
const AuthenticatedCfoIndexRoute = AuthenticatedCfoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCfoRoute,
} as any)
const AuthenticatedCeoIndexRoute = AuthenticatedCeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCeoRoute,
} as any)
const AuthenticatedFinanceValidationRoute =
  AuthenticatedFinanceValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceReconciliationRoute =
  AuthenticatedFinanceReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceMastersRoute =
  AuthenticatedFinanceMastersRouteImport.update({
    id: '/masters',
    path: '/masters',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedCfoPnlRoute = AuthenticatedCfoPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedCfoRoute,
} as any)
const AuthenticatedCfoInvoicesRoute =
  AuthenticatedCfoInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedCfoRoute,
  } as any)
const AuthenticatedCfoAuditRoute = AuthenticatedCfoAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedCfoRoute,
} as any)
const AuthenticatedCfoApprovalsRoute =
  AuthenticatedCfoApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedCfoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo': typeof AuthenticatedCeoRouteWithChildren
  '/cfo': typeof AuthenticatedCfoRouteWithChildren
  '/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/it': typeof AuthenticatedItRouteWithChildren
  '/operations': typeof AuthenticatedOperationsRouteWithChildren
  '/cfo/approvals': typeof AuthenticatedCfoApprovalsRoute
  '/cfo/audit': typeof AuthenticatedCfoAuditRoute
  '/cfo/invoices': typeof AuthenticatedCfoInvoicesRoute
  '/cfo/pnl': typeof AuthenticatedCfoPnlRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/masters': typeof AuthenticatedFinanceMastersRoute
  '/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/finance/validation': typeof AuthenticatedFinanceValidationRoute
  '/ceo/': typeof AuthenticatedCeoIndexRoute
  '/cfo/': typeof AuthenticatedCfoIndexRoute
  '/facilities/': typeof AuthenticatedFacilitiesIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/it/': typeof AuthenticatedItIndexRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cfo/approvals': typeof AuthenticatedCfoApprovalsRoute
  '/cfo/audit': typeof AuthenticatedCfoAuditRoute
  '/cfo/invoices': typeof AuthenticatedCfoInvoicesRoute
  '/cfo/pnl': typeof AuthenticatedCfoPnlRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/masters': typeof AuthenticatedFinanceMastersRoute
  '/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/finance/validation': typeof AuthenticatedFinanceValidationRoute
  '/ceo': typeof AuthenticatedCeoIndexRoute
  '/cfo': typeof AuthenticatedCfoIndexRoute
  '/facilities': typeof AuthenticatedFacilitiesIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/it': typeof AuthenticatedItIndexRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRouteWithChildren
  '/_authenticated/cfo': typeof AuthenticatedCfoRouteWithChildren
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/it': typeof AuthenticatedItRouteWithChildren
  '/_authenticated/operations': typeof AuthenticatedOperationsRouteWithChildren
  '/_authenticated/cfo/approvals': typeof AuthenticatedCfoApprovalsRoute
  '/_authenticated/cfo/audit': typeof AuthenticatedCfoAuditRoute
  '/_authenticated/cfo/invoices': typeof AuthenticatedCfoInvoicesRoute
  '/_authenticated/cfo/pnl': typeof AuthenticatedCfoPnlRoute
  '/_authenticated/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance/masters': typeof AuthenticatedFinanceMastersRoute
  '/_authenticated/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/_authenticated/finance/validation': typeof AuthenticatedFinanceValidationRoute
  '/_authenticated/ceo/': typeof AuthenticatedCeoIndexRoute
  '/_authenticated/cfo/': typeof AuthenticatedCfoIndexRoute
  '/_authenticated/facilities/': typeof AuthenticatedFacilitiesIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/it/': typeof AuthenticatedItIndexRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ceo'
    | '/cfo'
    | '/facilities'
    | '/finance'
    | '/it'
    | '/operations'
    | '/cfo/approvals'
    | '/cfo/audit'
    | '/cfo/invoices'
    | '/cfo/pnl'
    | '/finance/invoices'
    | '/finance/masters'
    | '/finance/reconciliation'
    | '/finance/validation'
    | '/ceo/'
    | '/cfo/'
    | '/facilities/'
    | '/finance/'
    | '/it/'
    | '/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cfo/approvals'
    | '/cfo/audit'
    | '/cfo/invoices'
    | '/cfo/pnl'
    | '/finance/invoices'
    | '/finance/masters'
    | '/finance/reconciliation'
    | '/finance/validation'
    | '/ceo'
    | '/cfo'
    | '/facilities'
    | '/finance'
    | '/it'
    | '/operations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ceo'
    | '/_authenticated/cfo'
    | '/_authenticated/facilities'
    | '/_authenticated/finance'
    | '/_authenticated/it'
    | '/_authenticated/operations'
    | '/_authenticated/cfo/approvals'
    | '/_authenticated/cfo/audit'
    | '/_authenticated/cfo/invoices'
    | '/_authenticated/cfo/pnl'
    | '/_authenticated/finance/invoices'
    | '/_authenticated/finance/masters'
    | '/_authenticated/finance/reconciliation'
    | '/_authenticated/finance/validation'
    | '/_authenticated/ceo/'
    | '/_authenticated/cfo/'
    | '/_authenticated/facilities/'
    | '/_authenticated/finance/'
    | '/_authenticated/it/'
    | '/_authenticated/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/it': {
      id: '/_authenticated/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof AuthenticatedItRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cfo': {
      id: '/_authenticated/cfo'
      path: '/cfo'
      fullPath: '/cfo'
      preLoaderRoute: typeof AuthenticatedCfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsRoute
    }
    '/_authenticated/it/': {
      id: '/_authenticated/it/'
      path: '/'
      fullPath: '/it/'
      preLoaderRoute: typeof AuthenticatedItIndexRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/facilities/': {
      id: '/_authenticated/facilities/'
      path: '/'
      fullPath: '/facilities/'
      preLoaderRoute: typeof AuthenticatedFacilitiesIndexRouteImport
      parentRoute: typeof AuthenticatedFacilitiesRoute
    }
    '/_authenticated/cfo/': {
      id: '/_authenticated/cfo/'
      path: '/'
      fullPath: '/cfo/'
      preLoaderRoute: typeof AuthenticatedCfoIndexRouteImport
      parentRoute: typeof AuthenticatedCfoRoute
    }
    '/_authenticated/ceo/': {
      id: '/_authenticated/ceo/'
      path: '/'
      fullPath: '/ceo/'
      preLoaderRoute: typeof AuthenticatedCeoIndexRouteImport
      parentRoute: typeof AuthenticatedCeoRoute
    }
    '/_authenticated/finance/validation': {
      id: '/_authenticated/finance/validation'
      path: '/validation'
      fullPath: '/finance/validation'
      preLoaderRoute: typeof AuthenticatedFinanceValidationRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/reconciliation': {
      id: '/_authenticated/finance/reconciliation'
      path: '/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof AuthenticatedFinanceReconciliationRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/masters': {
      id: '/_authenticated/finance/masters'
      path: '/masters'
      fullPath: '/finance/masters'
      preLoaderRoute: typeof AuthenticatedFinanceMastersRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/invoices': {
      id: '/_authenticated/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/cfo/pnl': {
      id: '/_authenticated/cfo/pnl'
      path: '/pnl'
      fullPath: '/cfo/pnl'
      preLoaderRoute: typeof AuthenticatedCfoPnlRouteImport
      parentRoute: typeof AuthenticatedCfoRoute
    }
    '/_authenticated/cfo/invoices': {
      id: '/_authenticated/cfo/invoices'
      path: '/invoices'
      fullPath: '/cfo/invoices'
      preLoaderRoute: typeof AuthenticatedCfoInvoicesRouteImport
      parentRoute: typeof AuthenticatedCfoRoute
    }
    '/_authenticated/cfo/audit': {
      id: '/_authenticated/cfo/audit'
      path: '/audit'
      fullPath: '/cfo/audit'
      preLoaderRoute: typeof AuthenticatedCfoAuditRouteImport
      parentRoute: typeof AuthenticatedCfoRoute
    }
    '/_authenticated/cfo/approvals': {
      id: '/_authenticated/cfo/approvals'
      path: '/approvals'
      fullPath: '/cfo/approvals'
      preLoaderRoute: typeof AuthenticatedCfoApprovalsRouteImport
      parentRoute: typeof AuthenticatedCfoRoute
    }
  }
}

interface AuthenticatedCeoRouteChildren {
  AuthenticatedCeoIndexRoute: typeof AuthenticatedCeoIndexRoute
}

const AuthenticatedCeoRouteChildren: AuthenticatedCeoRouteChildren = {
  AuthenticatedCeoIndexRoute: AuthenticatedCeoIndexRoute,
}

const AuthenticatedCeoRouteWithChildren =
  AuthenticatedCeoRoute._addFileChildren(AuthenticatedCeoRouteChildren)

interface AuthenticatedCfoRouteChildren {
  AuthenticatedCfoApprovalsRoute: typeof AuthenticatedCfoApprovalsRoute
  AuthenticatedCfoAuditRoute: typeof AuthenticatedCfoAuditRoute
  AuthenticatedCfoInvoicesRoute: typeof AuthenticatedCfoInvoicesRoute
  AuthenticatedCfoPnlRoute: typeof AuthenticatedCfoPnlRoute
  AuthenticatedCfoIndexRoute: typeof AuthenticatedCfoIndexRoute
}

const AuthenticatedCfoRouteChildren: AuthenticatedCfoRouteChildren = {
  AuthenticatedCfoApprovalsRoute: AuthenticatedCfoApprovalsRoute,
  AuthenticatedCfoAuditRoute: AuthenticatedCfoAuditRoute,
  AuthenticatedCfoInvoicesRoute: AuthenticatedCfoInvoicesRoute,
  AuthenticatedCfoPnlRoute: AuthenticatedCfoPnlRoute,
  AuthenticatedCfoIndexRoute: AuthenticatedCfoIndexRoute,
}

const AuthenticatedCfoRouteWithChildren =
  AuthenticatedCfoRoute._addFileChildren(AuthenticatedCfoRouteChildren)

interface AuthenticatedFacilitiesRouteChildren {
  AuthenticatedFacilitiesIndexRoute: typeof AuthenticatedFacilitiesIndexRoute
}

const AuthenticatedFacilitiesRouteChildren: AuthenticatedFacilitiesRouteChildren =
  {
    AuthenticatedFacilitiesIndexRoute: AuthenticatedFacilitiesIndexRoute,
  }

const AuthenticatedFacilitiesRouteWithChildren =
  AuthenticatedFacilitiesRoute._addFileChildren(
    AuthenticatedFacilitiesRouteChildren,
  )

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinanceMastersRoute: typeof AuthenticatedFinanceMastersRoute
  AuthenticatedFinanceReconciliationRoute: typeof AuthenticatedFinanceReconciliationRoute
  AuthenticatedFinanceValidationRoute: typeof AuthenticatedFinanceValidationRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinanceMastersRoute: AuthenticatedFinanceMastersRoute,
  AuthenticatedFinanceReconciliationRoute:
    AuthenticatedFinanceReconciliationRoute,
  AuthenticatedFinanceValidationRoute: AuthenticatedFinanceValidationRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedItRouteChildren {
  AuthenticatedItIndexRoute: typeof AuthenticatedItIndexRoute
}

const AuthenticatedItRouteChildren: AuthenticatedItRouteChildren = {
  AuthenticatedItIndexRoute: AuthenticatedItIndexRoute,
}

const AuthenticatedItRouteWithChildren = AuthenticatedItRoute._addFileChildren(
  AuthenticatedItRouteChildren,
)

interface AuthenticatedOperationsRouteChildren {
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
}

const AuthenticatedOperationsRouteChildren: AuthenticatedOperationsRouteChildren =
  {
    AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
  }

const AuthenticatedOperationsRouteWithChildren =
  AuthenticatedOperationsRoute._addFileChildren(
    AuthenticatedOperationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRouteWithChildren
  AuthenticatedCfoRoute: typeof AuthenticatedCfoRouteWithChildren
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRouteWithChildren
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedItRoute: typeof AuthenticatedItRouteWithChildren
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCeoRoute: AuthenticatedCeoRouteWithChildren,
  AuthenticatedCfoRoute: AuthenticatedCfoRouteWithChildren,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRouteWithChildren,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedItRoute: AuthenticatedItRouteWithChildren,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
