/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedItRouteImport } from './routes/_authenticated/it'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated/facilities'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedCfoIndexRouteImport } from './routes/_authenticated/cfo.index'
import { Route as AuthenticatedFinanceValidationRouteImport } from './routes/_authenticated/finance.validation'
import { Route as AuthenticatedFinanceReconciliationRouteImport } from './routes/_authenticated/finance.reconciliation'
import { Route as AuthenticatedFinanceMastersRouteImport } from './routes/_authenticated/finance.masters'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated/finance.invoices'
import { Route as AuthenticatedCfoPnlRouteImport } from './routes/_authenticated/cfo.pnl'
import { Route as AuthenticatedCfoInvoicesRouteImport } from './routes/_authenticated/cfo.invoices'
import { Route as AuthenticatedCfoAuditRouteImport } from './routes/_authenticated/cfo.audit'
import { Route as AuthenticatedCfoApprovalsRouteImport } from './routes/_authenticated/cfo.approvals'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItRoute = AuthenticatedItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCfoIndexRoute = AuthenticatedCfoIndexRouteImport.update({
  id: '/cfo/',
  path: '/cfo/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceValidationRoute =
  AuthenticatedFinanceValidationRouteImport.update({
    id: '/finance/validation',
    path: '/finance/validation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceReconciliationRoute =
  AuthenticatedFinanceReconciliationRouteImport.update({
    id: '/finance/reconciliation',
    path: '/finance/reconciliation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceMastersRoute =
  AuthenticatedFinanceMastersRouteImport.update({
    id: '/finance/masters',
    path: '/finance/masters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/finance/invoices',
    path: '/finance/invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCfoPnlRoute = AuthenticatedCfoPnlRouteImport.update({
  id: '/cfo/pnl',
  path: '/cfo/pnl',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCfoInvoicesRoute =
  AuthenticatedCfoInvoicesRouteImport.update({
    id: '/cfo/invoices',
    path: '/cfo/invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCfoAuditRoute = AuthenticatedCfoAuditRouteImport.update({
  id: '/cfo/audit',
  path: '/cfo/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCfoApprovalsRoute =
  AuthenticatedCfoApprovalsRouteImport.update({
    id: '/cfo/approvals',
    path: '/cfo/approvals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/it': typeof AuthenticatedItRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/cfo/approvals': typeof AuthenticatedCfoApprovalsRoute
  '/cfo/audit': typeof AuthenticatedCfoAuditRoute
  '/cfo/invoices': typeof AuthenticatedCfoInvoicesRoute
  '/cfo/pnl': typeof AuthenticatedCfoPnlRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/masters': typeof AuthenticatedFinanceMastersRoute
  '/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/finance/validation': typeof AuthenticatedFinanceValidationRoute
  '/cfo/': typeof AuthenticatedCfoIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/it': typeof AuthenticatedItRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/cfo/approvals': typeof AuthenticatedCfoApprovalsRoute
  '/cfo/audit': typeof AuthenticatedCfoAuditRoute
  '/cfo/invoices': typeof AuthenticatedCfoInvoicesRoute
  '/cfo/pnl': typeof AuthenticatedCfoPnlRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/masters': typeof AuthenticatedFinanceMastersRoute
  '/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/finance/validation': typeof AuthenticatedFinanceValidationRoute
  '/cfo': typeof AuthenticatedCfoIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRoute
  '/_authenticated/it': typeof AuthenticatedItRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/cfo/approvals': typeof AuthenticatedCfoApprovalsRoute
  '/_authenticated/cfo/audit': typeof AuthenticatedCfoAuditRoute
  '/_authenticated/cfo/invoices': typeof AuthenticatedCfoInvoicesRoute
  '/_authenticated/cfo/pnl': typeof AuthenticatedCfoPnlRoute
  '/_authenticated/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance/masters': typeof AuthenticatedFinanceMastersRoute
  '/_authenticated/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/_authenticated/finance/validation': typeof AuthenticatedFinanceValidationRoute
  '/_authenticated/cfo/': typeof AuthenticatedCfoIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ceo'
    | '/facilities'
    | '/it'
    | '/operations'
    | '/cfo/approvals'
    | '/cfo/audit'
    | '/cfo/invoices'
    | '/cfo/pnl'
    | '/finance/invoices'
    | '/finance/masters'
    | '/finance/reconciliation'
    | '/finance/validation'
    | '/cfo/'
    | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ceo'
    | '/facilities'
    | '/it'
    | '/operations'
    | '/cfo/approvals'
    | '/cfo/audit'
    | '/cfo/invoices'
    | '/cfo/pnl'
    | '/finance/invoices'
    | '/finance/masters'
    | '/finance/reconciliation'
    | '/finance/validation'
    | '/cfo'
    | '/finance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ceo'
    | '/_authenticated/facilities'
    | '/_authenticated/it'
    | '/_authenticated/operations'
    | '/_authenticated/cfo/approvals'
    | '/_authenticated/cfo/audit'
    | '/_authenticated/cfo/invoices'
    | '/_authenticated/cfo/pnl'
    | '/_authenticated/finance/invoices'
    | '/_authenticated/finance/masters'
    | '/_authenticated/finance/reconciliation'
    | '/_authenticated/finance/validation'
    | '/_authenticated/cfo/'
    | '/_authenticated/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/it': {
      id: '/_authenticated/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof AuthenticatedItRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cfo/': {
      id: '/_authenticated/cfo/'
      path: '/cfo'
      fullPath: '/cfo/'
      preLoaderRoute: typeof AuthenticatedCfoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/validation': {
      id: '/_authenticated/finance/validation'
      path: '/finance/validation'
      fullPath: '/finance/validation'
      preLoaderRoute: typeof AuthenticatedFinanceValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/reconciliation': {
      id: '/_authenticated/finance/reconciliation'
      path: '/finance/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof AuthenticatedFinanceReconciliationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/masters': {
      id: '/_authenticated/finance/masters'
      path: '/finance/masters'
      fullPath: '/finance/masters'
      preLoaderRoute: typeof AuthenticatedFinanceMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/invoices': {
      id: '/_authenticated/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cfo/pnl': {
      id: '/_authenticated/cfo/pnl'
      path: '/cfo/pnl'
      fullPath: '/cfo/pnl'
      preLoaderRoute: typeof AuthenticatedCfoPnlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cfo/invoices': {
      id: '/_authenticated/cfo/invoices'
      path: '/cfo/invoices'
      fullPath: '/cfo/invoices'
      preLoaderRoute: typeof AuthenticatedCfoInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cfo/audit': {
      id: '/_authenticated/cfo/audit'
      path: '/cfo/audit'
      fullPath: '/cfo/audit'
      preLoaderRoute: typeof AuthenticatedCfoAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cfo/approvals': {
      id: '/_authenticated/cfo/approvals'
      path: '/cfo/approvals'
      fullPath: '/cfo/approvals'
      preLoaderRoute: typeof AuthenticatedCfoApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRoute
  AuthenticatedItRoute: typeof AuthenticatedItRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedCfoApprovalsRoute: typeof AuthenticatedCfoApprovalsRoute
  AuthenticatedCfoAuditRoute: typeof AuthenticatedCfoAuditRoute
  AuthenticatedCfoInvoicesRoute: typeof AuthenticatedCfoInvoicesRoute
  AuthenticatedCfoPnlRoute: typeof AuthenticatedCfoPnlRoute
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinanceMastersRoute: typeof AuthenticatedFinanceMastersRoute
  AuthenticatedFinanceReconciliationRoute: typeof AuthenticatedFinanceReconciliationRoute
  AuthenticatedFinanceValidationRoute: typeof AuthenticatedFinanceValidationRoute
  AuthenticatedCfoIndexRoute: typeof AuthenticatedCfoIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCeoRoute: AuthenticatedCeoRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRoute,
  AuthenticatedItRoute: AuthenticatedItRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedCfoApprovalsRoute: AuthenticatedCfoApprovalsRoute,
  AuthenticatedCfoAuditRoute: AuthenticatedCfoAuditRoute,
  AuthenticatedCfoInvoicesRoute: AuthenticatedCfoInvoicesRoute,
  AuthenticatedCfoPnlRoute: AuthenticatedCfoPnlRoute,
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinanceMastersRoute: AuthenticatedFinanceMastersRoute,
  AuthenticatedFinanceReconciliationRoute:
    AuthenticatedFinanceReconciliationRoute,
  AuthenticatedFinanceValidationRoute: AuthenticatedFinanceValidationRoute,
  AuthenticatedCfoIndexRoute: AuthenticatedCfoIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
